title: "No Reason Needed"
description: "A mathematics blog"

url: "https://ahram12.github.io"
baseurl: "/noreasonneeded.github.io"

markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge